In [1]:
import Gmsh: gmsh;

gmsh.initialize();

gmsh.open("cylinder_2d.msh");

Info    : Reading 'cylinder_2d.msh'...
Info    : 18 entities
Info    : 23577 nodes
Info    : 4482 elements
Info    : Done reading 'cylinder_2d.msh'


In [2]:
node_tags, node_coords, node_params = gmsh.model.mesh.getNodes();

In [3]:
node_tags_ = Int64.(node_tags)

23577-element Vector{Int64}:
     1
     2
     3
     4
     5
     6
     7
     8
     9
    10
     ⋮
 23569
 23570
 23571
 23572
 23573
 23574
 23575
 23576
 23577

In [4]:
node_coords_ = Matrix(reshape(node_coords, (3, Int(length(node_coords) / 3)))')

23577×3 Matrix{Float64}:
 -5.0      -5.0       0.0
  5.0      -5.0       0.0
  5.0       5.0       0.0
 -5.0       5.0       0.0
 -1.0       0.0       0.0
  0.0      -1.0       0.0
  1.0       0.0       0.0
  0.0       1.0       0.0
 -4.5      -5.0       0.0
 -4.0      -5.0       0.0
  ⋮                   
 -1.21105   0.673077  0.0
 -1.15339   0.665957  0.0
 -1.17663   0.679381  0.0
 -1.18759   0.660035  0.0
 -1.16413   0.646993  0.0
 -1.22545   0.707572  0.0
 -1.25101   0.722339  0.0
 -1.26267   0.70177   0.0
 -1.23686   0.687423  0.0

In [5]:
node_coords

70731-element Vector{Float64}:
 -5.0
 -5.0
  0.0
  5.0
 -5.0
  0.0
  5.0
  5.0
  0.0
 -5.0
  ⋮
 -1.251014506844682
  0.7223387337743065
  0.0
 -1.262667805856165
  0.7017695880421789
  0.0
 -1.236860266819379
  0.6874233354536556
  0.0

In [6]:
gmsh.model.mesh.getElementsByType(36, 1)

(UInt64[0x0000000000000e03, 0x0000000000000e04, 0x0000000000000e05, 0x0000000000000e06, 0x0000000000000e07, 0x0000000000000e08, 0x0000000000000e09, 0x0000000000000e0a, 0x0000000000000e0b, 0x0000000000000e0c  …  0x0000000000001179, 0x000000000000117a, 0x000000000000117b, 0x000000000000117c, 0x000000000000117d, 0x000000000000117e, 0x000000000000117f, 0x0000000000001180, 0x0000000000001181, 0x0000000000001182], UInt64[0x0000000000000007, 0x0000000000000320, 0x0000000000000407, 0x00000000000001b3, 0x000000000000411a, 0x000000000000411b, 0x000000000000411c, 0x000000000000411d, 0x000000000000411e, 0x000000000000411f  …  0x00000000000030d8, 0x00000000000030d7, 0x00000000000049ab, 0x00000000000049aa, 0x0000000000005c11, 0x0000000000005c10, 0x0000000000005c16, 0x0000000000005c17, 0x0000000000005c18, 0x0000000000005c19])

In [7]:
elemTypes, elemTags, elemNodeTags = gmsh.model.mesh.getElements(2, 1)

(Int32[21, 36], Vector{UInt64}[[0x00000000000000d1, 0x00000000000000d2, 0x00000000000000d3, 0x00000000000000d4, 0x00000000000000d5, 0x00000000000000d6, 0x00000000000000d7, 0x00000000000000d8, 0x00000000000000d9, 0x00000000000000da  …  0x0000000000000df9, 0x0000000000000dfa, 0x0000000000000dfb, 0x0000000000000dfc, 0x0000000000000dfd, 0x0000000000000dfe, 0x0000000000000dff, 0x0000000000000e00, 0x0000000000000e01, 0x0000000000000e02], [0x0000000000000e03, 0x0000000000000e04, 0x0000000000000e05, 0x0000000000000e06, 0x0000000000000e07, 0x0000000000000e08, 0x0000000000000e09, 0x0000000000000e0a, 0x0000000000000e0b, 0x0000000000000e0c  …  0x0000000000001179, 0x000000000000117a, 0x000000000000117b, 0x000000000000117c, 0x000000000000117d, 0x000000000000117e, 0x000000000000117f, 0x0000000000001180, 0x0000000000001181, 0x0000000000001182]], Vector{UInt64}[[0x0000000000000915, 0x0000000000000b92, 0x000000000000060e, 0x0000000000000c22, 0x0000000000000c23, 0x0000000000000c24, 0x0000000000000c25, 0x

In [8]:
elemTypes

2-element Vector{Int32}:
 21
 36

In [9]:
Int64.(elemTags[1])

3378-element Vector{Int64}:
  209
  210
  211
  212
  213
  214
  215
  216
  217
  218
    ⋮
 3578
 3579
 3580
 3581
 3582
 3583
 3584
 3585
 3586

In [10]:
Int64.(elemTags[2])

896-element Vector{Int64}:
 3587
 3588
 3589
 3590
 3591
 3592
 3593
 3594
 3595
 3596
    ⋮
 4474
 4475
 4476
 4477
 4478
 4479
 4480
 4481
 4482

In [11]:
Int64.(elemNodeTags[2])

14336-element Vector{Int64}:
     7
   800
  1031
   435
 16666
 16667
 16668
 16669
 16670
 16671
     ⋮
 12503
 18859
 18858
 23569
 23568
 23574
 23575
 23576
 23577

In [12]:
Int.(elemNodeTags[1])

33780-element Vector{Int64}:
  2325
  2962
  1550
  3106
  3107
  3108
  3109
  3110
  3111
  3112
     ⋮
  3100
  2502
 16658
 16657
 11871
 11870
  4744
  4743
 16665

In [13]:
entities = gmsh.model.getEntities();
entities

18-element Vector{Tuple{Int32, Int32}}:
 (0, 1)
 (0, 2)
 (0, 3)
 (0, 4)
 (0, 5)
 (0, 6)
 (0, 7)
 (0, 8)
 (0, 9)
 (1, 1)
 (1, 2)
 (1, 3)
 (1, 4)
 (1, 5)
 (1, 6)
 (1, 7)
 (1, 8)
 (2, 1)

In [14]:
dim = entities[end][1]
tag = entities[end][2]

1

In [15]:
dim

2

In [16]:
tag

1

In [17]:
gmsh.model.getDimension()

2