In [1]:
import GaussQuadrature as gq;
order::Int64 = 3;
xi_int::Vector{Float64}, w_int::Vector{Float64} = gq.legendre(order);

In [2]:
n_mesh::Int64 = 20;
n_node::Int64 = n_mesh + 1;
x_begin::Float64 = -10.;
x_end::Float64 = 10.;
mesh1D::Vector{Float64} = LinRange(x_begin, x_end, n_node);

In [3]:
n_step::Int64 = 1000;
dt::Float64 = 0.01;
initial_function::Function = x->sin(x);

In [4]:
function mesh1DGaussIntegrate(mesh1D::Vector{Float64}, order::Int64)::Vector{Float64}
    xi_int::Vector{Float64}, w_int::Vector{Float64} = gq.legendre(order);
    N::Int64 = length(mesh1D);
    mesh1D_gauss::Vector{Float64} = zeros(Float64, order*(N-1));
    for i::Int64 = 1: N-1
        mesh1D_gauss[order*(i-1)+1: order*i] = (mesh1D[i+1] - mesh1D[i])/2 .* xi_int .+ (mesh1D[i+1] + mesh1D[i])/2;
    end
    return mesh1D_gauss;
end

mesh1DGaussIntegrate (generic function with 1 method)

In [5]:
mesh1D_gauss::Vector{Float64} = mesh1DGaussIntegrate(mesh1D, order);

In [6]:
mesh1D_gauss

60-element Vector{Float64}:
 -9.887298334620741
 -9.5
 -9.112701665379259
 -8.887298334620741
 -8.5
 -8.112701665379259
 -7.887298334620742
 -7.5
 -7.112701665379259
 -6.887298334620742
  ⋮
  7.112701665379258
  7.5
  7.887298334620741
  8.112701665379259
  8.5
  8.887298334620741
  9.112701665379259
  9.5
  9.887298334620741

In [12]:
gq.legendre(2)

([-0.5773502691896257, 0.5773502691896257], [1.0, 1.0])

In [13]:
gq.legendre(3)

([-0.7745966692414835, 4.2500725161431774e-17, 0.7745966692414834], [0.5555555555555557, 0.8888888888888888, 0.5555555555555559])

In [38]:
gq.legendre(3)

([-0.7745966692414835, 4.2500725161431774e-17, 0.7745966692414834], [0.5555555555555557, 0.8888888888888888, 0.5555555555555559])

In [15]:
import Gmsh

In [65]:
Gmsh.gmsh.initialize()
Gmsh.gmsh.model.mesh.getIntegrationPoints(3, "Gauss3")[2]

4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0

In [49]:
Gmsh.gmsh.model.mesh.getElementType("Hexahedron", 1)

5

In [72]:
Gmsh.gmsh.model.mesh.getBasisFunctions(2, [0, 0, 0], "H1Legendre1")[2]

18-element Vector{Float64}:
 1.0
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0
 0.0